name: check-structure

on: [workflow_call] # yamllint disable-line

permissions:
  # This is required for the commit count check.
  pull-requests: read
  repository-projects: read

jobs:
  commit_count_check:
    runs-on: ubuntu-latest
    steps:
    # https://github.com/marketplace/actions/github-api-request
    - uses: octokit/request-action@v2.x
      id: get_commit_count
      with:
        # https://docs.github.com/en/rest/pulls/pulls#list-commits-on-a-pull-request
        route: GET /repos/${{ github.event.repository.full_name }}/pulls/${{ github.event.number }}/commits # yamllint disable-line
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Log Commits
      run: |
        cat >./commits.log <<EOL
        ${{ steps.get_commit_count.outputs.data }}
        EOL
    - name: Check Single Commit
      run: jq '. | length' ./commits.log | xargs -I % test % -eq 1
