on: # yamllint disable-line
  workflow_call:
    inputs:
      devel:
        required: false
        type: boolean
        default: false
      prod:
        required: false
        type: boolean
        default: false
      python_version:
        required: false
        type: string
        default: "3.10"
      shared:
        required: false
        type: boolean
        default: false

# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
permissions:
  # This is required for AWS OIDC credential access.
  id-token: write
  # This is required for actions/checkout.
  contents: read

jobs:
  pipper_publish:
    runs-on: ubuntu-latest
    steps:
    # https://github.com/actions/checkout
    - uses: actions/checkout@v3
    # https://github.com/actions/setup-python
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python_version }}
    - name: Install Poetry
      run: pip install poetry
    # https://github.com/actions/cache
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/poetry
          ~/.cache/pip
        key: py-${{ inputs.python_version }}-${{ hashFiles('**/pyproject.toml', '**/poetry.lock', '**/pipper.json') }} # yamllint disable-line
        restore-keys: |
          py-${{ inputs.python_version }}-
    - name: Poetry Install
      run: |
        poetry config cache-dir ~/.cache/poetry
        poetry install
        poetry env info
    # https://github.com/aws-actions/configure-aws-credentials
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/cbrdata-devel-gh-pipper # yamllint disable-line
        aws-region: us-west-2
    - name: Pipper Installs
      run: |
        poetry run task pipper_update
        poetry run task pipper_update --dev
    - name: Pipper Bundle
      run: poetry run task pipper_bundle
    - name: Pipper Publish Devel
      if: inputs.devel
      run: poetry run task pipper_publish_devel
    - name: Pipper Shared Publish Devel
      if: inputs.devel && inputs.shared
      run: poetry run task pipper_shared_publish_devel
    - name: Pipper Publish Prod
      if: inputs.prod
      run: poetry run task pipper_publish
    - name: Pipper Shared Publish Prod
      if: inputs.prod && inputs.shared
      run: poetry run task pipper_shared_publish
