name: check-python

on: # yamllint disable-line
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
      check_quality:
        required: false
        type: boolean
        default: true
      test:
        required: false
        type: boolean
        default: true
      include_extras:
        required: false
        type: boolean
        default: true
      pydocstyle:
        required: false
        type: boolean
        default: true
      radon:
        required: false
        type: boolean
        default: true
      mypy:
        required: false
        type: boolean
        default: true
      flake8:
        required: false
        type: boolean
        default: true

# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
permissions:
  # This is required for AWS OIDC credential access.
  id-token: write
  # This is required for actions/checkout.
  contents: read

jobs:
  python_check:
    runs-on: ubuntu-latest
    steps:
    # https://github.com/actions/checkout
    - uses: actions/checkout@v4
    # Poetry must be installed before python setup for caching to work.
    # https://github.com/actions/setup-python/issues/369
    - name: Install Poetry
      run: pipx install poetry
    # https://github.com/actions/setup-python
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
        cache: poetry
    - name: Poetry Dependencies
      run: |
        poetry install ${{ inputs.include_extras  && '--all-extras' || '' }}
        poetry env info
    # https://github.com/aws-actions/configure-aws-credentials
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/gh-standard # yamllint disable-line
        aws-region: us-west-2
    - name: Pipper Dependencies
      run: |
        poetry run task pipper_update
        poetry run task pipper_update --dev
    - name: Flake8
      if: inputs.check_quality && inputs.flake8
      run: |
        poetry run flake8 --version
        poetry run task flake8
    - name: PyDocStyle
      if: inputs.check_quality && inputs.pydocstyle
      run: |
        poetry run pydocstyle --version
        poetry run task pydocstyle
    - name: Radon
      if: inputs.check_quality && inputs.radon
      run: poetry run task radon
    - name: MyPy
      if: inputs.check_quality && inputs.mypy
      run: |
        poetry run mypy --version
        poetry run task mypy
    - name: Task Test
      if: inputs.test
      run: poetry run task test
